In [55]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
movie_data=pd.read_csv('movies.csv')
movie_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [57]:
selected_features=['genres','keywords','overview','tagline','cast','crew','director']
# print(selected_features)

for feature in selected_features:
    movie_data[feature]=movie_data[feature].fillna('')

combined_features=''
for feature in selected_features:
    combined_features+=movie_data[feature]+' '
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Name: genres, Length: 4803, dtype: object


In [58]:
vectorizer=TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 29040)	0.017904551998245716
  (0, 143439)	0.017904551998245716
  (0, 237207)	0.017904551998245716
  (0, 215999)	0.01408925578640511
  (0, 20877)	0.017904551998245716
  (0, 114014)	0.017904551998245716
  (0, 187180)	0.006802461874914445
  (0, 20876)	0.017078092070968928
  (0, 114013)	0.017904551998245716
  (0, 236705)	0.017078092070968928
  (0, 20875)	0.017904551998245716
  (0, 114012)	0.017904551998245716
  (0, 231293)	0.017904551998245716
  (0, 20874)	0.017078092070968928
  (0, 114010)	0.017904551998245716
  (0, 223396)	0.017078092070968928
  (0, 220855)	0.009792762982380084
  (0, 20873)	0.017904551998245716
  (0, 114008)	0.017904551998245716
  (0, 217952)	0.017904551998245716
  (0, 227197)	0.013938201434126649
  (0, 20872)	0.017904551998245716
  (0, 114005)	0.017904551998245716
  (0, 215481)	0.01603687570135683
  (0, 214555)	0.012926313642166402
  :	:
  (4802, 200177)	0.035750751181951076
  (4802, 201056)	0.03236975292814213
  (4802, 204348)	0.03626111379649456
  (4802, 219016)

In [59]:
similarity=cosine_similarity(feature_vectors)
print(similarity)
similarity.shape

[[1.         0.56834966 0.82296573 ... 0.31300601 0.06959855 0.1368497 ]
 [0.56834966 1.         0.57434866 ... 0.28437939 0.0658672  0.12297724]
 [0.82296573 0.57434866 1.         ... 0.32746201 0.07881012 0.13982208]
 ...
 [0.31300601 0.28437939 0.32746201 ... 1.         0.0528671  0.08890457]
 [0.06959855 0.0658672  0.07881012 ... 0.0528671  1.         0.03856326]
 [0.1368497  0.12297724 0.13982208 ... 0.08890457 0.03856326 1.        ]]


(4803, 4803)

In [68]:
# Model steps combined
movie_name=input('Enter the movie you like:')
list_of_all_titles=movie_data['title'].tolist()
close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=close_match[0]
ind_of_movie=movie_data[movie_data['title']==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[ind_of_movie]))
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print('Movies similar to',close_match,' for you:\n')
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    title=movie_data[movie_data['index']==index]['title'].values[0]
    print(i,end='')
    print('.',title)
    i+=1
    if i>30:
        break

Movies similar to Transamerica  for you:

1. Transamerica
2. Alexander
3. The Bourne Supremacy
4. Collateral Damage
5. The Bourne Ultimatum
6. Kill Bill: Vol. 1
7. Catwoman
8. Around the World in 80 Days
9. Austin Powers in Goldmember
10. The Aviator
11. Bad Boys II
12. The Chronicles of Riddick
13. The League of Extraordinary Gentlemen
14. Sahara
15. Black Hawk Down
16. Hulk
17. Minority Report
18. The Dark Knight Rises
19. Cursed
20. Master and Commander: The Far Side of the World
21. Harry Potter and the Philosopher's Stone
22. Terminator 3: Rise of the Machines
23. Knight and Day
24. Kill Bill: Vol. 2
25. The Butterfly Effect
26. The Alamo
27. Blade
28. The Polar Express
29. John Q
30. Harry Potter and the Chamber of Secrets


In [69]:
movie_name=input('Enter the movie you like:')
print(movie_name)

captain america


In [70]:
list_of_all_titles=movie_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [71]:
close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(close_match)
close_match=close_match[0]
print(close_match)

['Transamerica', 'Mi America', 'Captain America: Civil War']
Transamerica


In [63]:
ind_of_movie=movie_data[movie_data['title']==close_match]['index'].values[0]
print(ind_of_movie)

728


In [64]:
similarity_score=list(enumerate(similarity[ind_of_movie]))
print(similarity_score)
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(0, 0.7597778775713444), (1, 0.5796062915009554), (2, 0.7617414202297726), (3, 0.7816121449732802), (4, 0.7388977804252522), (5, 0.6323860632638288), (6, 0.6304414211291309), (7, 0.692684740079506), (8, 0.5347331535140449), (9, 0.7412313448839267), (10, 0.46809117192105587), (11, 0.40918633445674035), (12, 0.5104335454723349), (13, 0.5435383977895628), (14, 0.6413747973492239), (15, 0.6975845652527787), (16, 0.7492716264733721), (17, 0.5922348479540527), (18, 0.44760931646742524), (19, 0.754232625331028), (20, 0.7316415695099826), (21, 0.4459103014328309), (22, 0.7436150068058027), (23, 0.5560698949843736), (24, 0.5983858798181535), (25, 0.6326066814418738), (26, 0.7575167900555451), (27, 0.7478487985706957), (28, 0.7960167762513801), (29, 0.5302181644085008), (30, 0.7655354194866559), (31, 0.5609026104181903), (32, 0.46245569041752427), (33, 0.6220701480961619), (34, 0.37871925227834285), (35, 0.6679805480641567), (36, 0.7087740084116684), (37, 0.5675063801263094), (38, 0.73928639088

In [65]:
print('Movies suggested for you:\n')
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    title=movie_data[movie_data['index']==index]['title'].values[0]
    print(i,end='')
    print('.',title)
    i+=1
    if i>30:
        break

Movies suggested for you:

1. Hellboy
2. Blade II
3. The Core
4. The Day After Tomorrow
5. Jurassic World
6. The League of Extraordinary Gentlemen
7. Cursed
8. Master and Commander: The Far Side of the World
9. War of the Worlds
10. Contact
11. Catwoman
12. Minority Report
13. Alexander
14. Blade: Trinity
15. Harry Potter and the Chamber of Secrets
16. The Dark Knight Rises
17. xXx
18. The Wolf of Wall Street
19. Bad Boys II
20. Harry Potter and the Prisoner of Azkaban
21. Freddy vs. Jason
22. The Bourne Supremacy
23. Terminator 3: Rise of the Machines
24. AVP: Alien vs. Predator
25. Hulk
26. End of Days
27. Black Hawk Down
28. Deep Blue Sea
29. The Aviator
30. Harry Potter and the Philosopher's Stone
